/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import DAO.serializar;
import DAO.tablaDAO;
import Entidad.Conectar;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.ObjectInputFilter.Config;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class InicioSesion extends javax.swing.JFrame {
    String idEmpleado =null;
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Visual/iconACTIVIDAD.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        lblContrasena = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Iniciar Sesion");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");

        lblUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblUsuarioKeyTyped(evt);
            }
        });

        jButton2.setText("Config");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        lblContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblContrasenaActionPerformed(evt);
            }
        });
        lblContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblContrasenaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblContrasenaKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 138, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButton2)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try{
            serializar serializar = new serializar ();
            Conectar conectar = new Conectar ();
            String BD =serializar.deserializarObjeto("BD.dat",String.class);
            String login = serializar.deserializarObjeto("Login.dat",String.class);
            String Pass = serializar.deserializarObjeto("Pass.dat",String.class);
            String URL = serializar.deserializarObjeto("URL.dat",String.class);
            conectar.setVariableGlobal(BD, login, Pass, URL);
            tablaDAO x= new tablaDAO ();
            idEmpleado=x.InicioUsuario(lblUsuario.getText(), lblContrasena.getText());
             String idRol=x.InicioAdmin(lblUsuario.getText(), lblContrasena.getText());
            System.out.println(idEmpleado);
            if (idRol!=null){
                MenuPrivado1 TA = new MenuPrivado1 ();
            
           
            
            TA.setVisible(true);
            
            dispose();    
            }
            else if (idEmpleado != null){
                MenuPublico RA = new MenuPublico ();
            RA.setIdEmpleado(Integer.parseInt(idEmpleado));
            System.out.println("ANTES"+idEmpleado);
            
            RA.setVisible(true);
            
            dispose();    
            }
            else {
                JOptionPane.showMessageDialog(null, "No se encontró usuario registrado", "Error", JOptionPane.ERROR_MESSAGE);

            }
            
        
        }
        catch (Exception e){
                JOptionPane.showMessageDialog(null, "Error al iniciar sesión: "+e, "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Configuracion conf = new Configuracion ();
            conf.setVisible(true);
            
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        // Habilita el botón cuando se presiona Enter
        jButton1.setEnabled(true);
    }
    }//GEN-LAST:event_jButton1KeyPressed

    private void lblContrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblContrasenaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        // Habilita el botón cuando se presiona Enter
        jButton1.setEnabled(true);
    }
    }//GEN-LAST:event_lblContrasenaKeyPressed

    private void lblUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblUsuarioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        // Habilita el botón cuando se presiona Enter
        jButton1.setEnabled(true);
    }
    }//GEN-LAST:event_lblUsuarioKeyPressed

    private void lblContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblContrasenaActionPerformed
        // TODO add your handling code here:
      if (evt.getSource() == jButton1) {
   jButton1.setEnabled(true);
    }
    }//GEN-LAST:event_lblContrasenaActionPerformed

    private void lblUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblUsuarioKeyTyped
        // TODO add your handling code here:
        char teclaPresionada = evt.getKeyChar();
          if (teclaPresionada == KeyEvent.VK_ENTER) {
        jButton1.doClick();
        try{
            serializar serializar = new serializar ();
            Conectar conectar = new Conectar ();
            String BD =serializar.deserializarObjeto("BD.dat",String.class);
            String login = serializar.deserializarObjeto("Login.dat",String.class);
            String Pass = serializar.deserializarObjeto("Pass.dat",String.class);
            String URL = serializar.deserializarObjeto("URL.dat",String.class);
            conectar.setVariableGlobal(BD, login, Pass, URL);
            tablaDAO x= new tablaDAO ();
            idEmpleado=x.InicioUsuario(lblUsuario.getText(), lblContrasena.getText());
             String idRol=x.InicioAdmin(lblUsuario.getText(), lblContrasena.getText());
            System.out.println(idEmpleado);
            if (idRol!=null){
                MenuPrivado1 TA = new MenuPrivado1 ();
            
           
            
            TA.setVisible(true);
            
            dispose();    
            }
            else if (idEmpleado != null){
                MenuPublico RA = new MenuPublico ();
            RA.setIdEmpleado(Integer.parseInt(idEmpleado));
            System.out.println("ANTES"+idEmpleado);
            
            RA.setVisible(true);
            
            dispose();    
            }
            else {
                JOptionPane.showMessageDialog(null, "No se encontró usuario registrado", "Error", JOptionPane.ERROR_MESSAGE);

            }
            
        
        }
        catch (Exception e){
                JOptionPane.showMessageDialog(null, "Error al iniciar sesión: "+e, "Error", JOptionPane.ERROR_MESSAGE);

        }
        jButton1.setEnabled(true);
    }
    }//GEN-LAST:event_lblUsuarioKeyTyped

    private void lblContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblContrasenaKeyTyped
        // TODO add your handling code here:
        char teclaPresionada = evt.getKeyChar();
          if (teclaPresionada == KeyEvent.VK_ENTER) {
        jButton1.doClick();
        try{
            serializar serializar = new serializar ();
            Conectar conectar = new Conectar ();
            String BD =serializar.deserializarObjeto("BD.dat",String.class);
            String login = serializar.deserializarObjeto("Login.dat",String.class);
            String Pass = serializar.deserializarObjeto("Pass.dat",String.class);
            String URL = serializar.deserializarObjeto("URL.dat",String.class);
            conectar.setVariableGlobal(BD, login, Pass, URL);
            tablaDAO x= new tablaDAO ();
            idEmpleado=x.InicioUsuario(lblUsuario.getText(), lblContrasena.getText());
             String idRol=x.InicioAdmin(lblUsuario.getText(), lblContrasena.getText());
            System.out.println(idEmpleado);
            if (idRol!=null){
                MenuPrivado1 TA = new MenuPrivado1 ();
            
           
            
            TA.setVisible(true);
            
            dispose();    
            }
            else if (idEmpleado != null){
                MenuPublico RA = new MenuPublico ();
            RA.setIdEmpleado(Integer.parseInt(idEmpleado));
            System.out.println("ANTES"+idEmpleado);
            
            RA.setVisible(true);
            
            dispose();    
            }
            else {
                JOptionPane.showMessageDialog(null, "No se encontró usuario registrado", "Error", JOptionPane.ERROR_MESSAGE);

            }
            
        
        }
        catch (Exception e){
                JOptionPane.showMessageDialog(null, "Error al iniciar sesión: "+e, "Error", JOptionPane.ERROR_MESSAGE);

        }
        jButton1.setEnabled(true);
    }
    }//GEN-LAST:event_lblContrasenaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField lblContrasena;
    private javax.swing.JTextField lblUsuario;
    // End of variables declaration//GEN-END:variables
}
