/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import DAO.comboBOX;
import DAO.tablaDAO;
import Entidad.Actividad;
import Tabla.imprimirTabla;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;


/**
 *
 * @author ADMIN
 */
public class TablaActividades extends javax.swing.JFrame {
     ArrayList<String> listaNombresEmpleado=  new ArrayList<>();
     ArrayList<String> listaIdEmpleado = new ArrayList<>();
    /**
     * Creates new form TablaActividades
     */
 public TablaActividades() {
        initComponents();
        comboBOX x = new comboBOX();
        
        imprimirTabla y = new imprimirTabla();
        listarEmpleadoCB(CBNombre);
        y.visualizar_tabla_Actividades_Total(tableActividades);
        setLocationRelativeTo(null);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Visual/iconACTIVIDAD.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableActividades = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CBNombre = new javax.swing.JComboBox<>();
        lblFecha = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        tableActividades.setAutoCreateRowSorter(true);
        tableActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableActividades.setEnabled(false);
        tableActividades.setFocusable(false);
        tableActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableActividadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableActividades);

        jButton1.setBackground(new java.awt.Color(204, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setText("Nombre :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Fecha Registro:");

        CBNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("volver al Menú");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton4.setText("Actualizar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton2)
                .addGap(291, 291, 291)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(112, 112, 112))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(CBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(300, 300, 300))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(CBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
 imprimirTabla x = new imprimirTabla();


int indice = CBNombre.getSelectedIndex();
System.out.println("INDICE=="+indice);
 Date utilDate = lblFecha.getDate();
 for (int i = 0; i < listaNombresEmpleado.size(); i++) {
        System.out.println(listaNombresEmpleado.get(i));
    }
    System.out.println("xxxxxxxxxxx");

    for (int i = 0; i < listaIdEmpleado.size(); i++) {
        System.out.println(listaIdEmpleado.get(i));
    }
    System.out.println("fin");
if (utilDate != null && indice>0) {
    
    java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                System.out.println("Filtro0");

    System.out.println(indice);
    System.out.println(listaIdEmpleado.get(indice - 1));
    System.out.println("inicio");

    for (int i = 0; i < listaNombresEmpleado.size(); i++) {
        System.out.println(listaNombresEmpleado.get(i));
    }
    System.out.println("xxxxxxxxxxx");

    for (int i = 0; i < listaIdEmpleado.size(); i++) {
        System.out.println(listaIdEmpleado.get(i));
    }
    System.out.println("fin");

    // Convertir java.util.Date a java.sql.Date
   

    System.out.println(sqlDate);
    x.visualizar_tabla_Filtrada_Actividades(tableActividades, Integer.valueOf(listaIdEmpleado.get(indice - 1)), sqlDate);
} 
else if (indice ==0 && utilDate!=null){
            System.out.println("Filtro1");
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

        x.visualizar_tabla_Filtrada_Actividades_Fecha(tableActividades,sqlDate);
    }
    
    else if (utilDate == null && indice>0 ) {
            System.out.println("Filtro2");
            System.out.println(Integer.valueOf(listaIdEmpleado.get(indice-1)));
                x.visualizar_tabla_Filtrada_Actividades_Empleado(tableActividades, Integer.valueOf(listaIdEmpleado.get(indice-1)));

        // Aquí puedes manejar el caso cuando utilDate es null
    }
    else{
                System.out.println("Nada");
                            System.out.println("Filtro3");
                x.visualizar_tabla_Actividades_Total(tableActividades);
    }
    }//GEN-LAST:event_jButton1MouseClicked
private String dateToString(Date date) {
    if (date != null) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(date);
    } else {
        return null;
    }
}
    private void tableActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableActividadesMouseClicked
        // TODO add your handling code here:
   tablaDAO tablaDAO = new tablaDAO();

    if (evt.getClickCount() == 2) {
        int column = tableActividades.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tableActividades.getRowHeight();

        if (row < tableActividades.getRowCount() && row >= 0 && column < tableActividades.getColumnCount() && column >= 0) {
            int id = (int) tableActividades.getValueAt(row, 0);

            // Obtener la fecha como tipo Date
            Date fecha = (Date) tableActividades.getValueAt(row, 6);

            // Crear una instancia de InfoDato
            DetalleActividadAdmin DatosPanel = new DetalleActividadAdmin();
            Actividad actividad_x = tablaDAO.obtenerDatosActividad(id);
            DatosPanel.setActividad(actividad_x); // Pasar la fecha como parámetro

            // Mostrar la ventana emergente
            DatosPanel.setLocationRelativeTo(null);
            DatosPanel.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Cerrar solo esta ventana al cerrar
            DatosPanel.setVisible(true);
        }
    }
    }//GEN-LAST:event_tableActividadesMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        imprimirTabla x = new imprimirTabla();
        x.visualizar_tabla_Actividades_Total(tableActividades);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        MenuPrivado1 AE = new MenuPrivado1 ();

        AE.setVisible(true);

        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaActividades().setVisible(true);
            }
        });
    }
        public void listarEmpleadoCB(JComboBox<String> CB) {
                comboBOX y = new comboBOX ();

            Map<String, String> mapaProyectos = y.listarComboBoxEmpleado();
                   listaNombresEmpleado= new ArrayList<>(y.listarComboBoxEmpleado().keySet());
                    listaIdEmpleado = new ArrayList<>(y.listarComboBoxEmpleado().values());

                DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
                comboBoxModel.addElement("");
                for (String elemento : mapaProyectos.keySet()) {
                    comboBoxModel.addElement(elemento);
                }

                CB.setModel(comboBoxModel);
            }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser lblFecha;
    private javax.swing.JTable tableActividades;
    // End of variables declaration//GEN-END:variables
}
